title: LoriSchlatter.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio website for Lori Schlatter, non-profit professional turned data science student with Lambda School
image: https://github.com/lorischl-otter/lorischl-otter.github.io/blob/master/assets/img/default.png?raw=true
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "lorischlatter.com" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lori Schlatter # add your name
author-img: headshot.jpg # add your photo
about-author: Nonprofit Professional turned Data Science Student with Lambda School # add description
# social-facebook: # add your Facebook handle
social-github: lorischl-otter # add your Github handle
social-linkedin: LoriSchlatter # add your Linkedin handle
social-twitter: lorischl_otter
social-email: lori.schlatter@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-151766017-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
